name: sdk_int
description: This plugin lets you get the Current SDK version for android. It includes all version codes to compare with.
version: 0.0.1
repository: https://github.com/TamilKannanCV/sdk_int.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tk.sdk_int
        pluginClass: SdkIntPlugin
